spring:
  application:
    name: uni-article-api
    servlet:
      multipart:
        max-file-size: 100MB
        max-request-size: 100MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud_class?useSSL=false&allowMultiQueries=true
    username: root
    password: root

server:
  port: 8080

mybatis:
  type-aliases-package: com.yj.orm.domain
  configuration:
    map-underscore-to-camel-case: true  # mybatis开启驼峰式命名


dozer:
  mapping-files: classpath:/dozer/dozer-mapping.xml